In [12]:
import numpy as np
from dt_apriltags import Detector
import matplotlib.pyplot as plt
import cv2

In [13]:
at_detector = Detector(families='tag36h11',
                       nthreads=1,
                       quad_decimate=1.0,
                       quad_sigma=0.0,
                       refine_edges=1,
                       decode_sharpening=0.25,
                       debug=0)

In [44]:
photo = "2023-07-31-165657"
img = cv2.imread("/home/ebenq/Pictures/Webcam/" + photo + ".jpg")

# plt.imshow(img)
cameraMatrix = np.array([ 1060.71, 0, 960, 0, 1060.71, 540, 0, 0, 1]).reshape((3,3))

camera_params = ( cameraMatrix[0,0], cameraMatrix[1,1], cameraMatrix[0,2], cameraMatrix[1,2] )

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
tags = at_detector.detect(gray, estimate_tag_pose=True, camera_params=camera_params, tag_size=True)
print(tags[0].pose_R)

[[ 0.99967309 -0.02518052  0.00443445]
 [ 0.02524081  0.99958183 -0.01410898]
 [-0.00407733  0.0142163   0.99989063]]
